version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - SA_PASSWORD=T9u@Z4m!pR7#qFs2
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - docflow_net       # ✅ добавлено
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "T9u@Z4m!pR7#qFs2" -Q "SELECT 1" -C || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  seq:
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    networks:
      - docflow_net

  docflow-api:
    build:
      context: ../backend
      dockerfile: Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AgroFlowConnection=Server=mssql;Database=AgroFlowDB;User=sa;Password=T9u@Z4m!pR7#qFs2;TrustServerCertificate=True
    ports:
      - "8080:8080"
    depends_on:
      mssql:
        condition: service_healthy
    networks:
      - docflow_net

  docflow-frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - docflow-api
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api/v1
    networks:
      - docflow_net

volumes:
  mssql_data:

networks:
  docflow_net:
    driver: bridge